### ISSUE TITLE
Doesn't work with "mezzanine" django

### ISSUE THREAD

**Issue by altryne** [dghubble/django-unslashed#2]
For some reason, just adding the mezzanine middleware classes makes this aweosme middleware to stop working.

**Comment by redlolgeerf** [comment]
This happens, because url for mezzanine.pages.views.page consumes trailing slashes.
If you try to access /page/, mezzanine assumes, that "page/" is a slug, so no redirect happens.
The only workaround I see is ammending mezzanine.pages.urls
