### ISSUE TITLE
Broken in recent Django versions

### ISSUE THREAD

**Issue by MatthiasPortzel** [dghubble/django-unslashed#5]
Attempting to use this middleware in recent Django version gives the following error: `TypeError: object() takes no parameters`. I'm not an expert at Django's code nor middleware, but I'm guessing this comes from a change in how a Middleware class inherits.
This error can be fixed by adding `from django.utils.deprecation import MiddlewareMixin` to the top of the middleware.py file and changing the class signature to `class RemoveSlashMiddleware(MiddlewareMixin):`; which is what CommonMiddleware does.
I would be willing to make this change and PR, but I want to see if the original creator @dghubble is willing to merge and if the `pip` package could be updated.

**Comment by genereese** [comment]
Just seconding this issue. Would like to use this package but it's currently broken with the above-reported error.

**Comment by dghubble** [comment]
Unarchiving just to cleanup issues/PRs. This project is archived.
